# -*- coding: utf-8 -*-
"""1day.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BXeVLj0CXOOEqdWxptLv9RLNHgc9Y5Gi
"""

name=input("Vishal Gautam :- ")
salary1=float(input("Enter your first salary :- "))
salary2=float(input("Enter your second salary :- "))
salary=salary1+salary2
print("Okey",name,"your total salary is ",salary)